services:
    client:
        build: 
            context: .
            dockerfile: Dockerfile
        ports: 
            - 8080:3000
        volumes: 
            - ./src/:/app/src/
    server:
        build: ./server
        ports: 
            - 5001:5000
        command: npm run dev
        volumes: 
            - ./server/src/:/app/src/
    mongodb:
        image: mongo
        volumes: 
            - ./data:/data/db